global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']